### ISSUE TITLE
the HVSRWEB Isn't reading my mseed file

### ISSUE THREAD

**Issue by melahmad** [jpvantassel/hvsrweb#4]
Hi Dear,

So i have this Mseed file having 3 component data. When i press calculate, i am getting nothing.

[GDLC DARFIELD.zip](https://github.com/jpvantassel/hvsrweb/files/9059535/GDLC.DARFIELD.zip)

On geopsy you can see the file having a 3 component data (attached image).

![image](https://user-images.githubusercontent.com/108778999/177668729-dc96db6e-d5fd-47cb-b803-2db2328ff29d.png)

Is there anything am doing wrong.

**Comment by jpvantassel** [comment]
Hi @melahmad,

The file you uploaded is not `miniSEED` it is `.sac` developed for use with the [Seismic Analysis Code](https://ds.iris.edu/files/sac-manual/). Currently _hvsrweb_ only supports `miniSEED` format.

All the best,
Joe

**Comment by melahmad** [comment]
Hi Thanks Dear, yeah originally it was Sac (in the previous image) and then i exported it using geopsy to miniseed format which i attached in the previous zip file.

**Comment by jpvantassel** [comment]
Hi @melahmad,

Thank you for the clarification. I took a look at the data and from what I can tell it appears to be related to the frequency-domain rejection algorithm Cox et al. (2020). If you turn this off (under the HVSR tab) the HVSR curve computes without an issue. Results shown below:


All the best,
Joe

**Comment by melahmad** [comment]
Thank you Dear, Much Appreciated.
