### ISSUE TITLE
ERROR: No matching distribution found for hvsrpy>=2.0.0-rc.1

### ISSUE THREAD

**Issue by alecomunian** [jpvantassel/hvsrweb#7]
Unfortunately I was unable to install locally the software following the instructions provided on the site.
When running `pip install -r requirements.txt` the following error appears:

> ERROR: Could not find a version that satisfies the requirement hvsrpy>=2.0.0-rc.1 (from versions: 1.0.0rc0, 1.0.0)
> ERROR: No matching distribution found for hvsrpy>=2.0.0-rc.1
> 

I tried first a Python 3.10 virtual environment, but also Python 3.9 does not work (tried this because I realized that 3.10 does not appear in the hvsrpy list).

Thank you in advance and kind regards,

Alessandro

**Comment by jpvantassel** [comment]
Hi @alecomunian,

The code should work with hvsrpy v2.0.0 released in July. If you do `pip install hvsrpy==2.0.0` with the other requirements that should do the trick.

**Comment by alecomunian** [comment]
Thank you very much!
Now, by additionally installing in a fresh Python virtual environment ``xgboost``, ``scikit-learn`` and ``ipython`` it worked.
Thank you and kind regards,
Alessandro
