### ISSUE TITLE
Problem reading SAF v1 format file

### ISSUE THREAD

**Issue by GiusCalamita** [jpvantassel/hvsrweb#8]
Hi @jpvantassel ,
as requested, I am opening this issue here to remind you about a similar issue in HVSRpy resolved in the following link

[https://github.com/jpvantassel/hvsrpy/issues/28](url)

**Comment by jpvantassel** [comment]
Hi @GiusCalamita,

I have updated HVSRweb and was able to process the SAF data you provided with Issue 28 on _hvsrpy_. Let me know if you run into any issues.

Thanks!
Joe
